In [10]:
import numpy as np
from scipy import sparse

In [54]:
# Create matrix
matrix = np.array([[0,0,3], [1,0,2], [2,4,5]])
matrix

array([[0, 0, 3],
       [1, 0, 2],
       [2, 4, 5]])

In [55]:
# CSR (Compressed sparse row)
matrix_sparse = sparse.csr_matrix(matrix)
print (matrix_sparse)
#position -> value
#(1, 0) -> 	1
#(2, 0) -> 	2
#(2, 1) -> 	4

  (0, 2)	3
  (1, 0)	1
  (1, 2)	2
  (2, 0)	2
  (2, 1)	4
  (2, 2)	5


In [56]:
# check element in matrix
print (matrix[1])       # filter second row, no filter to column 
print (matrix[:,1])     # no filter to row, filter second column
print (matrix[-1,-1]) # last element in row, last element in column

[1 0 2]
[0 0 4]
5


In [57]:
# show shape
matrix.shape

(3, 3)

In [58]:
# show size(num of elements)
matrix.size

9

In [59]:
# show dimensions
matrix.ndim

2

In [60]:
# calculate all elements in matrix
matrix +100

array([[100, 100, 103],
       [101, 100, 102],
       [102, 104, 105]])

In [61]:
# find max, min 
print ("max in the matrix: {}".format(np.max(matrix)))
print (np.max(matrix, axis=1)) # along each row
print (np.max(matrix, axis=0)) # along each column

max in the matrix: 5
[3 2 5]
[2 4 5]


In [62]:
# calculate mean, var, std
print ("mean: {}".format(np.max(matrix)))
print ("std: {}".format(np.var(matrix)))

mean: 5
std: 2.9876543209876543


In [65]:
# reshape
# print (matrix.reshape(2,3))
print (matrix.reshape(-1))

[0 0 3 1 0 2 2 4 5]


In [66]:
# matrix transformation
print (matrix.T)

[[0 1 2]
 [0 0 4]
 [3 2 5]]


In [67]:
# create flatten matrix
print (matrix.reshape(-1))
print (matrix.flatten())

[0 0 3 1 0 2 2 4 5]
[0 0 3 1 0 2 2 4 5]


In [68]:
# calculate determinant
np.linalg.det(matrix)

12.0

In [78]:
# get diagonal (able to get with offset)
print (matrix)
print ("\n")
print (matrix.diagonal())
print (matrix.diagonal(offset=1))

[[0 0 3]
 [1 0 2]
 [2 4 5]]


[0 0 5]
[0 2]


In [79]:
# calculati diagonal elements sum
print (matrix.trace())
print (sum(matrix.diagonal()))

5
5


In [83]:
# eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print (eigenvalues)
print ("\n")
print (eigenvectors)

[ 7.1819708+0.j         -1.0909854+0.69325423j -1.0909854-0.69325423j]


[[ 0.36808835+0.j         -0.85812752+0.j         -0.85812752-0.j        ]
 [ 0.29664396+0.j         -0.01176884+0.35604652j -0.01176884-0.35604652j]
 [ 0.88119994+0.j          0.3120682 -0.19830018j  0.3120682 +0.19830018j]]


In [87]:
# calculate innrer product
print (np.dot(matrix, matrix))
print ("\n")
print (matrix @ matrix)

[[ 6 12 15]
 [ 4  8 13]
 [14 20 39]]


[[ 6 12 15]
 [ 4  8 13]
 [14 20 39]]


In [88]:
# calculate inverse matrix
np.linalg.inv(matrix)

array([[-0.66666667,  1.        ,  0.        ],
       [-0.08333333, -0.5       ,  0.25      ],
       [ 0.33333333,  0.        ,  0.        ]])

In [89]:
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [5.55111512e-17, 0.00000000e+00, 1.00000000e+00]])